#
# Makefile for DECnet netfilter modules
#

obj-$(CONFIG_RTP_RELAY) += relay.o
relay-objs := relay_core.o relay_dsp.o relay_in.o relay_ioctl.o relay_match.o relay_netlink.o relay_out.o relay_qos.o relay_rtp.o
