obj-$(CONFIG_SUNXI_RTL8370) += rtl8370_drv.o
rtl8370_drv-objs := rtl8370.o rtk_api.o rtl8370_asicdrv_mirror.o ../rtk_acl.o rtl8370_acl.o rtl8370_asicdrv_cputag.o rtl8370_asicdrv.o \
		rtl8370_asicdrv_phy.o rtl8370_asicdrv_port.o rtl8370_asicdrv_svlan.o rtl8370_asicdrv_meter.o smi.o rtl8370_asicdrv_lut.o \
		rtl8370_asicdrv_qos.o rtl8370_asicdrv_scheduling.o rtl8370_asicdrv_trunking.o rtl8370_asicdrv_mib.o rtl8370_asicdrv_vlan.o \
		rtl8370_asicdrv_dot1x.o
